[project]
name = "gradescope-autograder-template"
version = "0.1.0"
description = "Example autograder project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradescope-utils>=0.5.0",
]
